SegmentInfoCommon.h:43:17: error: unknown type name 'time_t'
Signed-off-by: Rémi Denis-Courmont <remi@remlab.net>
(cherry picked from commit aeb7c4c45d003fae1d777787bc264ecef6ad51db)